accordproject/markdown-editor

package-lock.json
package.json
src/editor/FormatToolbar.js
src/editor/MarkdownEditor.js
src/index.css

add some styling

---

src/MarkdownToSlateConverter.js
src/SlateToMarkdownConverter.js
src/index.js

Issue #4 and #5 from https://github.com/accordproject/markdown-editor/issues

onEnter lists and quote bug fixed

---

examples/src/index.css
package-lock.json
src/index.js
src/markdown/fromMarkdown.js
src/markdown/index.js
src/markdown/toMarkdown.js
src/plugins/list.js
src/schema.js

Revamped index, toMarkdown and fromMarkdown
Signed-off-by: ajmeraharsh <ajmera.harsh@gmail.com>

made plugins modular

---

package-lock.json
package.json
src/html/fromHTML.js
src/index.js
src/markdown/toMarkdown.js
src/plugins/list.js

Headings toMarkdown fixed
Signed-off-by: ajmeraharsh <ajmera.harsh@gmail.com>

pasteHTML added

---

.travis.yml

(fix) Wrong repo name in .travis.yml

---

.travis/deploy.sh

(fix) Extra '$' in deploy script

---

package.json

(fix) Add package.json targets

---

package-lock.json
package.json

(fix) Add semver/moment as dev dependencies

---

src/index.js

(feature) props to say whether to show Edit button

---

src/SlateAsInputEditor/index.js

fix(SlateAsInputEditor): edit useEffect hook so it does not cause loop

---

CHARTER.md
README.md

- Initiate Linux Foundation charter as a markdown file.
- N/A
- N/A

docs(CHARTER): implement linux foundation charter - I55

---

src/FormattingToolbar/index.js
src/SlateAsInputEditor/index.js

- added a serif font family for all headings including the toolbar. 
- Issue #<NUMBER HERE>

feat: add serif `font-family` for all headings

---

README.md

Signed-off-by: DEBSUBHRO <debsubhro.roy10@yahoo.com>
**Changes**
- Centering the title 
- Centering the badges
* Issue #79
* Pull Request #76

doc(Readme): Centering heading and labelled badges

---

README.md

- added license badge
- added build badge
- accordproject/techdocs/issues/82

docs(README): add license and build badge

---

README.md

Signed-off-by: Dmitry <daniloff200@gmail.com>
https://github.com/accordproject/techdocs/issues/80#issuecomment-544871864

fix(readme): fix broken link in table

---

package-lock.json
package.json

chore(dep) Upgrade to markdown-transform 0.6.0

---

src/SlateAsInputEditor/index.js

- Pass props into `EditorWrapper`
N/A
- Issue #124
- Pull Request #148

fix(src): pass shadow props

---

src/icons/navigation-left.js
src/icons/navigation-right.js

Fix area-label/type.
Find out about this when writing unit test.
- Change type to the correct one.

fix(icons): history aria-labels - I164

---

package-lock.json
package.json
src/FormattingToolbar/index.js

Fixes remaining issue from PR #159
- Bind methods to the component
- Vulnerabilities not fixed by `npm audit fix`
N/A

fix(*): correct bindings in hyperlink methods - I143

---

src/FormattingToolbar/index.js
src/schema.js

fix(schema): add tight property for lists

fix(schema): add tight property for lists

---

package-lock.json
package.json

chore(deps): remove unused react-flipcard dependency

chore(deps): remove unused react-flipcard dependency

---

src/SlateAsInputEditor/index.test.js

Signed-off-by: irmerk <jolenelanglinais@gmail.com>

chore(test): pause roundtrip test

---

package-lock.json
src/SlateAsInputEditor/index.js

fix(SlateAsInputEditor): disallow cut functionality if in uneditable text

fix(SlateAsInputEditor): disallow cut functionality if in uneditable text

---

package-lock.json
package.json

Signed-off-by: irmerk <jolenelanglinais@gmail.com>

chore(package): increment markdown-transform

---

package-lock.json
package.json
src/FormattingToolbar/index.js
src/SlateAsInputEditor/index.js

- Disable the toolbar and edits in `readOnly` mode
- N/A
- N/A

feat(src): disable toolbar and edits in readOnly

---

package-lock.json
package.json

- chore(deps): update transform deps to 0.9.5

chore(deps): update transform deps to 0.9.5

---

package-lock.json
package.json

chore(dep) Upgrade to Markdown Transform 0.9.7

---

package-lock.json
package.json

chore(dep) Upgrade to Markdown Transform 0.9.8

---

examples/src/index.js
src/SlateAsInputEditor/index.js
src/schema.js
src/styles.css

Signed-off-by: Dan Selman <danscode@selman.org>
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
- Issue #<NUMBER HERE>

(fix) debugging backspace issues with hr

---

examples/src/index.js
package-lock.json
package.json
src/SlateAsInputEditor/index.js

- chore(dep): update transform to 0.10.0
- See transform release notes here: https://github.com/accordproject/markdown-transform/releases/tag/v0.10.0

chore(dep): update transform to 0.10.0

---

README.md

fix(doc) Correct demo links in the README

---

package-lock.json
package.json
src/plugins/list.js

- Issue #229
- Pull Request #269

chore(plugins): undo pr 269

---

CONTRIBUTING.md
DEVELOPERS.md

- Point `CONTRIBUTING` and `DEVELOPERS` to `development` branch
- Update syncing `master` instructions
- Misc. cleanup

docs(*): point PRs to development

---

package-lock.json
package.json

- This PR is on master, switching to the latest markdown 0.10.4 release

chore(dep) Upgrade to latest markdown transform release 0.10.4

---

package.json

Signed-off-by: irmerk <jolenelanglinais@gmail.com>

chore(package): markdown-transform version

---

src/RichTextEditor/FormattingToolbar/HyperlinkButton.js
src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
src/RichTextEditor/index.js
src/RichTextEditor/plugins/withLinks.js

#325 
#327 
#328 
- First batch of bug fixes. Will continue working on the others separately.
- Issue #326 (starts addressing this but still more work to be done)

fix(HyperlinkModal): fixes #325, #327, and #328

---

examples/src/index.css
examples/src/index.js
src/RichTextEditor/FormattingToolbar/ToolbarMenu.js
src/RichTextEditor/FormattingToolbar/index.js
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap
src/RichTextEditor/tests/index.test.js
src/styles.css

Test PR #315 to merge into `accordproject:master`
- Make `ToolbarMenu` sticky.
- Need to test the changes in `cicero-ui`

feat(*): sticky formatting toolbar position - I314

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
src/RichTextEditor/plugins/withLinks.js

- fix(withLinks): preserve formatting when creating link

fix(withLinks): preserve formatting when creating link

---

src/RichTextEditor/FormattingToolbar/HyperlinkButton.js
src/RichTextEditor/FormattingToolbar/index.js
src/RichTextEditor/plugins/withLinks.js

- fix(Hyperlink): disallow adding link when formatting is not allowed and refactor wrapLink

fix(Hyperlink): disallow adding link when formatting is not allowed and refactor wrapLink

---

src/RichTextEditor/index.js
src/RichTextEditor/plugins/withLists.js
src/RichTextEditor/utilities/hotkeys.js

Handle adding new list items
- New HOF to handle list logic
- On enter, if in a `list_item`, create and insert a new `list_item`
- N/A
- Issue #321
- Pull Request #350

feat(RichTextEditor): handle breaking from list - I335

---

src/RichTextEditor/index.js

Force delete the selection if cutting

fix(RichTextEditor): delete fragment on cut - I331

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js

- Adds editor focus after the link removal.
- N/A
- N/A

fix(HyperlinkModal): fixed hotkey link removal undo - I352

---

package-lock.json
package.json

chore(deps): update transforms to 0.11.2

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
src/RichTextEditor/FormattingToolbar/index.js

- Capture window location and scroll to it after focusing on URL field
Relates to #380 - @elit-altum please check this PR

fix(*): fix issue for page jump on link modal open

---

src/MarkdownTextEditor/index.js
src/RichTextEditor/FormattingToolbar/index.js
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap
src/RichTextEditor/tests/index.test.js
src/styles.css

Swaps the `className` property for `id` on the editor and toolbar.

refactor(src): swap class for id

---

src/RichTextEditor/index.js

fix(RichTextEditor): update prop type
