src/SlateAsInputEditor/index.js

With this change, the demo example works so that if the markdown editor on the left is changed, the rich text editor on the right will re-render with the updated content.

feat(SlateAsInputEditor): update slate value when props change so Editor re-renders

---

package-lock.json
src/FormatToolbar.js
src/MarkdownEditor/index.js
src/SlateAsInputEditor/index.js
src/styles.css
src/toolbar.css

- CSS Grid
- Initialize grid css for toolbar 
- Improve grid css for main component
- Remove unnecessary grid css from both slate editor and markdown editor
- Enable classes for css and disable responsive vertical divider
- Will need further customization with Header button.
- Possible conflicts with how the editor has been split.

fix(FormatToolbar): correct responsive design for static toolbar - I48

---

examples/src/index.js
src/MarkdownAsInputEditor/index.js
src/SlateAsInputEditor/index.js

refactor(SlateAsInputEditor): refactor to always use props instead of setting state for slate val
refactor(MarkdownAsInputEditor): refactor to use props instead of setting state for md
fix(examples): update example demo based on changes

refactor(*): refactor editors to use props instead of setting state

---

src/MarkdownAsInputEditor/index.js

- Allows the user to pass a readOnly prop to the MarkdownAsInputEditor

feat(MarkdownAsInputEditor): add readOnly prop for MarkdownAsInputEditor

---

src/SlateAsInputEditor/index.js
src/schema.js

Signed-off-by: Dan Selman <danscode@selman.org>
This fix allows plugins to extend the Slate schema (to define custom block types, inlines, rules).

(fix) allow plugins to extend schema

---

src/icons/OL.js
src/icons/UL.js
src/icons/bold.js
src/icons/code.js
src/icons/hyperlink.js
src/icons/italic.js
src/icons/navigation-left.js
src/icons/navigation-right.js
src/icons/open-quote.js
src/icons/param.js
src/icons/underline.js

Correct toolbar icons misalignment in Safari
- Synchronize height and width of all icons
- These alignments (viewBox, height, width, padding) were quite finicky for each individual icon when first created, take a look to ensure they appear correct
- [Cicero UI 63](https://github.com/accordproject/cicero-ui/issues/63)

fix(icons): sync sizing for all toolbar icons - I62

---

src/SlateAsInputEditor/index.js

feat(SlateAsInputEditor): forward ref to the Slate Editor
This will allow us to access the slate Editor commands from the parent

 feat(SlateAsInputEditor): forward ref to the Slate Editor

---

src/FormattingToolbar/index.js

Signed-off-by: sgbj <scott.batary@gmail.com>
Creating a bulleted list marks a block as a hyperlink in the formatting toolbar.
- The code for rendering the link button was previously using `action.getSelectedListBlock(editor)` to determine whether the button should be marked as active. This has been changed to `action.hasLinks(editor)`.
- None
- None

Fix list blocks register as hyperlink (#84)

---

README.md

Signed-off-by: Aayush Bisen <aayush23101998@outlook.com>
Centered Accord Project Logo, adding the Slack badge, adding the License badge
- Centered logo of Accord Project in README
- Adding the Slack Badge in README
- Adding the license badge in README
- None
- https://github.com/accordproject/techdocs/issues/78
- https://github.com/accordproject/techdocs/issues/79
- https://github.com/accordproject/techdocs/issues/82

docs(README): centered logo, adds slack badge, adds license badge

---

README.md

issue #104 
Signed-off-by: Parikshit Hooda <phooda804@live.com>
changed the word 'components' to 'component' in README.md
- changed the word 'components' to 'component' in README.md
- Issue #104 

docs(README): fix typo - I104

---

src/FormattingToolbar/index.js
src/FormattingToolbar/toolbar.css
src/SlateAsInputEditor/index.js
src/html/fromHTML.js

Remove underline button from toolbar
- Comment out references to underline (left as placeholders for whenever #98 is resolved)
- Issue #98
Resolves #97

chore(*): comment out underline-related code - I97

---

src/SlateAsInputEditor/index.js

- feat(SlateAsInputEditor): pass props down to slate Editor
- this way, any props passed to SlateAsInputEditor will also get passed to the Editor from Slate

feat(SlateAsInputEditor): pass props down to slate Editor

---

README.md
examples/src/index.css
src/SlateAsInputEditor/index.js

Ability to style the blockquote text via a prop
- Added `BLOCKQUOTE` prop under `editorProps`
- `BLOCKQUOTE` prop can be used to style blockquotes in the document. `BLOCKQUOTE` prop supports following styles as of now: 
- `FONT_FAMILY`
- `FONT_COLOR`
- `FONT_SIZE`
- `FONT_STYLE`
- `FONT_WEIGHT`
- `QUOTE_COLOR`
Feature in action:
- The current props system for the blockquote is only for the text portion of the quote not for the entire quote itself, which includes styles for pseudoselectors.
- Issue #102

feat(*): add styling for blockquote - I102

---

src/SlateAsInputEditor/index.js

Signed-off-by: Artyom <artychen13@unist.ac.kr>
Fixes issue described in  [issue #135](https://github.com/accordproject/markdown-editor/issues/135).
This bug caused the following issue in [@accordproject/template-studio-v2 issue #113](https://github.com/accordproject/template-studio-v2/issues/113). Passed data-key from Heading Node was not set in heading html tags, as a result causing bugs when scrolling.
- [issue #135](https://github.com/accordproject/markdown-editor/issues/135)
- [@accordproject/template-studio-v2 issue #113](https://github.com/accordproject/template-studio-v2/issues/113)

fix(SlateAsInputEditor): set data-key for headings - I135

---

package.json
src/SlateAsInputEditor/index.test.js

Added Unit tests for the round trip conversion from normal text to markdown.
- Added Enzyme and Enzyme Adapter package
- Added test file with the default value and checking with expected and received.
Let me know if we need to add more tests.

test(SlateAsInputEditor): init unit tests for md output - I2

---

src/FormattingToolbar/index.js
src/FormattingToolbar/toolbarMethods.js

Replace js alert when setting the link to use popup 
- Not sure why the selection color gone once I select the text input.

feat(FormattingToolbar): implement hyperlink tooltip - I100

---

src/SlateAsInputEditor/index.js

These changes address the ability to escape out of either ordered or unordered list blocks back into a standard paragraph block when <kbd>ENTER</kbd> is pressed on a blank list item.
- Modifies the <kbd>ENTER</kbd> key handler to support the behaviour described above
Looks like the test infrastructure is in flux so I haven't added any integration tests to capture the new behaviour.

fix(SlateAsInputEditor): fix escaping out of list

---

DEVELOPERS.md

Typo in the git add upstream link
-Fixes the link from
https://github.com/acccordproject/markdown-editor.git to
https://github.com/accordproject/markdown-editor.git

fix(docs): typo in git upstream link - I151

---

src/FormattingToolbar/index.js
src/SlateAsInputEditor/index.js

Currently, formatting tools such as Bold, Italic is working although lockText is true.
Added checking on Editable before calling toggleMark

fix(FormattingToolbar): toolbar buttons work in locktext mode

---

README.md
src/SlateAsInputEditor/index.js

Added additional props for Shadow and border attributes
-  Added props for code flexibility
- Additional props for Border and Box-Shadow attributes of Markdown Editor
- Changed src/SlateAsInputEditor/index.js
- Issue #<NUMBER HERE>

feat(*): allow styling for shadow and border - I124

---

src/FormattingToolbar/index.js
src/SlateAsInputEditor/index.js

fix(FormattingToolbar): use editor.findDOMRange instead of importing it
Fixes this warning:

fix(FormattingToolbar): use editor.findDOMRange instead of importing it

---

package-lock.json
package.json
src/schema.js

Changes based on info from these two ([one][slack1] and [two][slack2]) conversations in SlateJS Slack
- Force a block after `'html_block'` to be a `'paragraph'`
- This should apply to `clause` blocks
- Unsure how to make the previous block a paragraph, `previous` did not work in addition to `next`
- There may be things other than `clause` blocks using `'html_block'`
- [TSv2 Issue #145][tsv2i]
- [TSv2 Pull Request #146][tsv2p]
[tsv2i]: https://github.com/accordproject/template-studio-v2/issues/145
[tsv2p]: https://github.com/accordproject/template-studio-v2/pull/146
[slack1]: https://slate-js.slack.com/archives/C1RH7AXSS/p1554819145354500
[slack2]: https://slate-js.slack.com/archives/C1RH7AXSS/p1555064971022200

feat(schema): force next block after html to paragraph

---

src/SlateAsInputEditor/index.js

fix(SlateAsInputEditor): always pass List and NoEdit plugins to editor

fix(SlateAsInputEditor): always pass List and NoEdit plugins to editor

---

src/FormattingToolbar/index.js

fix(FormattingToolbar): do not allow toolbar actions on text that should be locked
https://github.com/accordproject/cicero-ui/issues/211
https://github.com/accordproject/cicero-ui/issues/210
https://github.com/accordproject/cicero-ui/issues/209

fix(FormattingToolbar): do not allow toolbar actions on text that should be locked

---

src/FormattingToolbar/index.test.js

In this commit, I found that action had the correct aria text we
wanted, instead of type.
I wrote a jest test to prove that all the svg icons have unique aria
labels.
I tried running eslint, but it seems not to work for me.  I can
try to fix it, but I think that should be a separate task.
- <INSERT DESCRIPTION OF CHANGES>
- <SUB NOTES OF DESCRIPTIONS>
- <SUMMARIZE ALL COMMITS IN PULL REQUEST>
- Issue #<NUMBER HERE>

test(FormattingToolbar): init tests for buttons

---

src/SlateAsInputEditor/index.js

fix(SlateAsInputEditor): disallow paste if in non-editable text

fix(SlateAsInputEditor): disallow paste if in non-editable text

---

package-lock.json
package.json
src/FormattingToolbar/index.js
src/SlateAsInputEditor/index.js

feat(SlateAsInputEditor): add ability to pass onUndoOrRedo handler
- There is no way to access Slate's undo event directly, so I call the handler when a user uses the keyboard shortcut to undo/redo or clicks the icon in the toolbar. Refer to convo from Slate slack [here](https://slate-js.slack.com/archives/C1RH7AXSS/p1575921321010400).

feat(SlateAsInputEditor): add ability to pass onUndoOrRedo handler

---

package-lock.json
package.json
src/FormattingToolbar/index.js

- Pass a `'hyperlink'` type into `isEditable` for link button
- N/A
- [Cicero-UI #257](https://github.com/accordproject/cicero-ui/pull/257)

fix(FormattingToolbar): pass hyperlink type to link button

---

src/SlateAsInputEditor/index.js

on change gets called when editor is in read only mode
fix(SlateAsInputEditor): return from onChange if read only

fix(SlateAsInputEditor): return from onChange if read only

---

.babelrc
package-lock.json
package.json
src/SlateAsInputEditor/index.js
src/schema.js

Signed-off-by: Dan Selman <danscode@selman.org>
Allow backspace of a soft break.
- Render a softbreak as a `span` so that Slate can track the DOM
- Could not reproduce any issues with backspace inside lists in either Safari or Chrome
The code functions differently when running locally vs on Netlify.
https://deploy-preview-232--accordproject-markdown-editor.netlify.com/examples/
I see backspace issues when testing the Netlify version. Investigating...

(fix) backspace over a softbreak

---

src/SlateAsInputEditor/index.js
src/plugins/blockquote.js

- feat(blockquote): add ability to break out of block quote
I followed the same behavior that Slab has:
- Hitting enter empty line will break out of the block quote
- Backspacing on the last item when empty will break out of the block quote
#225 - The slate dom portion of issue 225 issue is giving me more trouble than I expected, so I will leave that for a separate PR (cc @jeromesimeon)

feat(blockquote): add ability to break out of block quote - 218

---

package-lock.json
package.json
src/schema.js

- Also addresses the markdown-editor side of https://github.com/accordproject/markdown-transform/issues/174

chore(dep) Upgrade to Markdown Transform 0.9.9, remove obsolete 'quote'

---

package-lock.json
package.json
src/SlateAsInputEditor/index.js

**Flags**
- HTML Inlines show as blue (styling?)
- Backspace deletes the whole inline, is that what we want?

chore(dep) Markdown Transform 0.9.10 ; Fix for html_inline node

---

src/MarkdownAsInputEditor/index.js
src/SlateAsInputEditor/index.js
src/styles.css
webpack.config.js

The use of global styles in `src/styles.css` such as `body { ... }` is not good practice because it could modify the global styling of client applications that use these components.
- Removed all `body` styles
- All other styles are now scoped to a class `ap-markdown-editor`

style: Make global styles scoped to components

---

examples/src/index.html
webpack.config.js

- Corrects URL for Semantic UI CSS in demo
- `index.html` is now in the top-level directory for the demo

fix(demo) Wrong URL for Semantic UI CSS in demo

---

src/FormattingToolbar/LinkComponent/index.js
src/FormattingToolbar/index.js

Modified popover when a link is clicked on
- The popover will have two UI, one when there is a link present in the text selected and others when there is no link
- When there is a link, it will show 3 buttons with the actions: Copy, Edit, Un-Link
- When there is no link, the previous Forn will be shown, i.e. A text-field for `href` and text with two action buttons, i.e. Save and unlink
- I have Added a state variable - `showLinkForm` to decide which UI should be shown, but the popover also depends on whether the selected is a link or not.
- The state variable was also added because I needed to prevent the focusing of the elements in the form when the form wasn't being rendered.
- The changes show a popover similar to Google Docs
Demo -
- Link preview (metadata / og metadata) couldn't be …

feat(FormattingToolbar): ability to open links - #213

---

src/FormattingToolbar/index.js
src/FormattingToolbar/toolbarTooltip.js
src/icons/bold.js
src/icons/code.js
src/icons/italic.js

- Added shortcut commands in `toolbarTooltip` based on OS of user
- Made the quote and link formatting options more descriptive
- Requires testing on MacOS and Linux platforms
- Issue #247

feat(toolbarTip): added shortcut commands in tooltip based on OS - I258

---

src/SlateAsInputEditor/index.js

Continues on the refactoring of Slate Inputs to object literals. 
The Hotkeys currently require a complex condition matching so they are still being handled by switch case while the rest of the conditions have been refactored to Object literals as they are safer and more comprehensive.
- Refactored three conditions to Object literals
- Issue #248

refactor(Slate): hotkey switch-case to object literal

---

src/plugins/list.js

- Changed ```list.js``` to break every element into an individual ```<li>``` tag rather than all children in a single tag
- The editor list is getting converted fine, but the individual children still aren't being converted to individual list items in the markdown. Currently working to fix that.
- Issue #229

fix(list): converts multiple line to lists - I229

---

src/SlateAsInputEditor/index.js

Removed the extra paragraph block which caused the spacing by inserting an empty text string
- Now an empty text string is added on hitting enter instead of a paragraph which also allows multiple line headings
- A backspace on the cursor before typing the heading on the new line converts it back into a paragraph.
- Not sure of the solution implemented would need a review
- Issue #280

fix(SlateAsInputEditor): removed blank line on hitting enter after heading - I280

---

src/FormattingToolbar/index.js
src/FormattingToolbar/toolbarTooltip.js
src/SlateAsInputEditor/index.js
src/icons/code.js
src/icons/navigation-right.js

- Changed the shortcut for ```code``` to ```Ctrl/Cmd+Shift+9```
- Also switched to using ```Shift``` instead of  ```⇧ ```  in tootips indicating the shortcuts, for improving user readability https://github.com/accordproject/markdown-editor/issues/290#issuecomment-598765720 
- Shifted from https://github.com/accordproject/markdown-editor/pull/291
- N/A

style(FormattingToolbar): changed order and shortcut for code - I289-290

---

README.md

Updated readme to show the new keyboard shortcuts
- The readme has the following text added just before the ### Demo section
------------------------------------------------
The keyboard shortcuts are as follows
Windows/Linux:
- Common actions
- `CTRL` + `C` - Copy
- `CTRL` + `X` - Cut
- `CTRL` + `V` - Paste
- `CTRL` + `Z` - Undo
- `CTRL` + `SHIFT` + `Z` - Redo
- `CTRL` + `Y` - Repeat last action
- Text formatting
- `CTRL` + `B` - Bold
- `CTRL` + `I` - Italicize 
- `CTRL` + `Q` - Block quotes
- `CTRL` + `SHIFT` + `9` - Code
- Paragraph formatting
- `CTRL` + `SHIFT` + `7` - Numbered list
- `CTRL` + `SHIFT` + `8` - Bulleted list
Mac:
- Common actions
- `⌘` + `C` - Copy
- `⌘` + `X` - Cut
- `⌘` + `V` - Paste
- `⌘` + `Z` - Undo
- `⌘` + `SHIFT` + `Z` - Redo
- `⌘` + `Y` - Repeat last action
- …

docs(readme): add keyboard shortcuts - #244

---

src/RichTextEditor/components/index.js
src/RichTextEditor/index.js
src/RichTextEditor/utilities/hotkeys.js

Pressing enter twice should escape a block(quote)
- Break from any current block type (UL, OL, Blockquote)
- If the current selection is an empty text node
- Correct the passing of `children` into elements
- Breaking from a list results in similar bugs to #323 and #335
- Issue #323
- Issue #335

feat(RichTextEditor): break from empty block on enter - I321

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js

Signed-off-by: Aman Sharma <mannu.poski10@gmail.com>
- Add a state `blankUrlError` to keep track of the URL if valid data is entered in the modal.
- If the URL is blank, error is displayed something like this:
- For further demonstration, here is a screencast:
- Instead of checking if the URL is empty, we should add RegEx to validate if it is a URL or not.

fix(HyperlinkModal.js): prevent insertion of links if URL is empty

---

src/styles.css

Fix `Markdown Editor` width so it doesn't overlap with `Rich Text Editor` on resizing.
- Set a `max-width` on `Markdown Editor`
- N/A

fix(styles): fix markdown editor width - I334

---

src/RichTextEditor/components/icons/link.js
src/RichTextEditor/index.js
src/RichTextEditor/utilities/hotkeys.js

Signed-off-by: Aman Sharma <mannu.poski10@gmail.com>
These changes aim to introduce a shortcut for adding hyperlinks.
- Change the label of icon to `Hyperlink (${MOD()}+K)`
- Add other entry for creating a shortcut `mod+k`.
- On pressing <kbd>Ctrl</kbd> + <kbd>k</kbd>, the editor will prompt for a URL.
- The demonstration is as follows.
~~- Please note that currently entering the URL using `insertLink` is broken. Look at the screencast below.
The URL converted is not in the correct markdown format.~~
I am sorry to cause confusion. The format is right. :sweat_smile:

feat(*): add shortcut for hyperlinking texts

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js
src/RichTextEditor/components/icons/copy.js
src/RichTextEditor/components/icons/delete.js
src/RichTextEditor/components/icons/open.js

- Added tooltips to the HyperlinkModal action icons using Semantic-UI Popup
Screenshot:
- Please review the tooltip messages. The current ones are:
- Copy Icon: Copy hyperlink text
- Remove Icon: Remove hyperlink
- Open Icon: Open link in a new tab
- Pull Request #351

feat(HyperlinkModal): added tooltips to action icons

---

README.md
examples/src/index.js
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap
src/RichTextEditor/tests/index.test.js

- `lockText` should only be used at the ContractEditor level in cicero-ui since it deals with the ability to edit clauses/variables
- it is no longer used by the markdown-editor specifically, so I have removed it

refactor(*): remove unused lockText prop

---

examples/src/index.css
examples/src/index.js
src/RichTextEditor/FormattingToolbar/ToolbarMenu.js
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap
src/RichTextEditor/tests/index.test.js
src/styles.css

feat(*): sticky formatting toolbar position - I314
Make `ToolbarMenu` sticky. Tests PR #315 to merge into `accordproject:master`
- `ToolbarMenu` is now sticky and takes the full width of the parent container. 
- N/A
- Issue #314 
- Pull Request #315

feat(*): sticky formatting toolbar position - I314

---

examples/src/index.css
examples/src/index.js
src/RichTextEditor/FormattingToolbar/ToolbarMenu.js
src/RichTextEditor/FormattingToolbar/index.js
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap
src/RichTextEditor/tests/index.test.js
src/styles.css

Make `ToolbarMenu` sticky
- `ToolbarMenu` is now sticky and attaches to the top of the editor on scroll
- N/A

feat(ToolbarMenu): sticky formatting toolbar position - I314

---

src/RichTextEditor/utilities/toolbarHelpers.js

Handle roundtrip action of toggling block types
- Unwraps all block types
- If the selection began as not a block, wrap in the format
- If the format is a list, wrap each child node in a `list_item`
- N/A

fix(utilities): handle block toggles - I323

---

src/RichTextEditor/components/index.js
src/RichTextEditor/utilities/generateId.js

- Adds `id` attributes to headings. The function for transforming the heading text into a viable anchor was taken from here: https://github.com/thlorenz/anchor-markdown-header/blob/87e4cca4618271e363f4af9697df0f73f23b3d3f/anchor-markdown-header.js#L20

feat(RichTextEditor): add ID to headings

---

package-lock.json
package.json
src/RichTextEditor/index.js
src/RichTextEditor/tests/__snapshots__/index.test.js.snap

- Upgrade to latest markdown transform
- Slate DOM has bold/italics annotations on parent node in some cases (instead of text node)
- Tested on demo for non-clauses
- Includes cloning Slate DOM when transforming to markdown to avoid immutability issues
- Includes fixes for https://github.com/accordproject/cicero-ui/issues/378 by @irmerk 
- Removes now unnecessary cloning in `handleCopyOrCut`
- Done minimal local testing

chore(dep) Upgrade to latest version of markdown transform

---

examples/src/index.css
examples/src/index.js

Signed-off-by: Arteev Raina <arteevraina@gmail.com>
Separate labels for `Markdown` and `Preview` have been added.
- Issue #345 #337 
- Previous Pull Request #367 
Please Review and suggest changes @irmerk @Michael-Grover @DianaLease :)

feat(demo): added labels for markdown and preview - I345

---

src/RichTextEditor/components/index.js
src/RichTextEditor/utilities/toolbarHelpers.js

- Previously when adding a heading, we would wrap the children nodes in a heading node, resulting in a paragraph inside of a heading
- Update type of node using `setNodes` instead of wrapping node if going from paragraph to heading or vice versa.
- Please test links in headings

fix(toolbarHelpers): update type of node  instead of wrapping node if updating heading style

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js

Signed-off-by: Nikhil <nikhilsharmarockstar21@gmail.com>
This PR adds the feature to insert `https://` if the URL does not start with a valid prefix
- Added logic for prefixing the URL with `https://` if the URL does not start with `http://` or `https://`

feat(hyperlink Modal): fix hyperlink modal accepts invalid urls

---

src/RichTextEditor/FormattingToolbar/HyperlinkModal.js

Put further protections in the hyperlink modal
- The remove link button does not need to determine if something is a link, the `unwrapLink` function does nothing if the selection is not a link
- `defaultLinkValue` was sometimes failing because there was no selection

fix(FormattingToolbar): prevent hyperlink crashing

---

src/RichTextEditor/index.js

Allow consumer of `markdown-editor` to prevent certain actions
- Sets groundwork for preventing `onKeyDown`
- Sets groundwork for preventing `onCopy` and `onCut`
- This will be done in conjunction with work in `cicero-ui` where the Contract Editor can prevent <kbd>BACKSPACE</kbd> when cursor is on the last node but the previous node is a smart clause template.
- This will also be done in conjunction with work in `cicero-ui` where the Contract Editor can prevent <kbd>CMD</kbd>+<kbd>C</kbd> and <kbd>CMD</kbd>+<kbd>X</kbd> when the selection begins or ends inside a smart clause template.
- N/A

feat(RichTextEditor): allow consumer to prevent actions
